### PR TITLE
aria-expanded values updated based on the callbacks

### PR DESCRIPTION
**Pull request by ajmaurya99**
### Description of the Change
The Aria Expanded value is not getting updated via `openSubmenu` and `closeSubmenu` callbacks, So I have updated the `aria-expanded` attribute based on the callbacks.

Also added `$submenu` reference to `onSubmenuOpen` and `onSubmenuClose` callbacks.
Added reference to the submenu on the `onSubmenuOpen()` callback.
Added reference to the submenu on the `onSubmenuClose()` callback.

### Benefits
Accessibility Enhancement.

### Verification Process

Open the Navigation dropdown menu item.
Click on the sibling menu item.
The aria-expanded value gets updated based on the openSubmenu and closeSubmenu callbacks.

### Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.

### Applicable Issues
https://github.com/10up/component-library/issues/106

### CODE REVIEW

**Comment by joesnellpdx** [comment]
Closing as duplicate of https://github.com/10up/component-library/pull/92

**Comment by tinacastillo1** [comment]
@joesnellpdx and @ajmaurya99 this branch has a solve for the aria-expanded issues listed above that the issue it was closed in favor for does not address. Could we re-open it and get it merged in? I've had to use this fix twice in the last week.

**Comment by jacobdubailcadmv** [comment]
I'm also seeing this issue on the latest version (2.1.3)

**Comment by ajmaurya99** [comment]
Thanks @tinacastillo1 @jacobdubailcadmv I will raise an updated PR in this week. Thanks for the report.

**Comment by ajmaurya99** [comment]
@tinacastillo1 @jacobdubailcadmv Could you both please confirm if this PR has the change that you were expecting.  Thanks :)

**Comment by jacobdubailcadmv** [comment]
> @tinacastillo1 @jacobdubailcadmv Could you both please confirm if this PR has the change that you were expecting. Thanks :)

This is working perfectly 😄

**Review by jacobdubailcadmv — APPROVED** [review]
Working for me locally

**Pull request merged**
