### PR TITLE
Navigation: Add $submenu reference to onSubmenuOpen callback

### LINKED ISSUE #28: Demo code missing site-menu-toggle class
**Describe the bug**
The example code for both HTML and Wordpress needs a site-menu-toggle class added to the main toggle element.

**To Reproduce**
1. Create a navigation output based on the markup provided.
2. Load the navigation in a browser window
3. Notice that on desktop, the navigation toggle still appears and its visibility isn't controlled by the script.

**Expected behavior**
When resizing from mobile to desktop, the navigation toggle should disappear, since it isn't required when the navigation becomes fully displayed.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version:  84.0.4147.105

**Additional context**
By adding the site-menu-toggle class to the main toggle "a" element, this issue should be resolved.

### LINKED ISSUE #29: Pass the submenu back to the call
**Is your feature request related to a problem? Please describe.**
Yes. There is a sort of problem.

When someone clicks a link that opens a submenu, the .submenu element toggles open with aria-hidden="false"
However the anchor item actually clicked (above the submenu element) gets no toggled-on class of any sort. It is not easy to style it for when it is open/closed.

I tried using the callbacks:

onSubmenuOpen: () => { //no way of getting to the current submenu opened },
onSubmenuClose: () => {},

However the callbacks are not being passed any parameters. So it is difficult to get the currently opened submenu and do things with it, or with adjacent siblings, like the clicked anchor.

**Describe the solution you'd like**
Please pass parameters for the callbacks like so:
Line 241 in navigation.js:
`this.settings.onSubmenuOpen.call(this, $submenu);`

Then I can use it like so:
onSubmenuOpen: (subMenu ) => { subMenu.previousElementSibling.classList.add('something') },

### PR DESCRIPTION
**Pull request by xavortm**
Fixes #29 

### Description of the Change
Add reference to the submenu on the `onSubmenuOpen()` callback.
Add reference to the submenu on the `onSubmenuClose()` callback.

### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ajmaurya99** [comment]
This is working as expected, can be deployed.

**Comment by saltcod** [comment]
@joesnellpdx and @nicholasio confirmed this as well.  Thoughts on merging?

**Review by joesnellpdx — DISMISSED** [review]

**Comment by joesnellpdx** [comment]
@nicholasio 

I want to get this merged, but there is an eslint error [here](https://github.com/10up/component-library/runs/5073407872?check_suite_focus=true)

Error: `Error: HttpError: Failed to generate URL to download artifact`

From the eslint job ([eslint.yml](https://github.com/10up/component-library/blob/develop/.github/workflows/eslint.yml))

I can't remember if this is a known issue and we can ignore - please confirm before I move this forward.

**Comment by joesnellpdx** [comment]
@ajmaurya99 

This has been merged and released to npm

**Pull request merged**
